
package cn.wuyl.sample.ws.helloworld;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://helloworld.ws.sample.wuyl.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://helloworld.ws.sample.wuyl.cn/", className = "cn.wuyl.sample.ws.helloworld.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://helloworld.ws.sample.wuyl.cn/", className = "cn.wuyl.sample.ws.helloworld.SayHelloResponse")
    @Action(input = "http://helloworld.ws.sample.wuyl.cn/HelloWorld/sayHelloRequest", output = "http://helloworld.ws.sample.wuyl.cn/HelloWorld/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayGoodbye", targetNamespace = "http://helloworld.ws.sample.wuyl.cn/", className = "cn.wuyl.sample.ws.helloworld.SayGoodbye")
    @ResponseWrapper(localName = "sayGoodbyeResponse", targetNamespace = "http://helloworld.ws.sample.wuyl.cn/", className = "cn.wuyl.sample.ws.helloworld.SayGoodbyeResponse")
    @Action(input = "http://helloworld.ws.sample.wuyl.cn/HelloWorld/sayGoodbyeRequest", output = "http://helloworld.ws.sample.wuyl.cn/HelloWorld/sayGoodbyeResponse")
    public String sayGoodbye(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
